In [1]:
# %load_ext autoreload
# %autoreload 2

# Import Libraries

In [2]:
from google.colab import drive
drive.mount('/content/drive')

path_gv = '/content/drive/MyDrive/tmp/'

Mounted at /content/drive

In [3]:
import sys

sys.path.append(path_gv)

In [4]:
import os


import pandas as pd
from torch.utils.data import DataLoader
from transformers import AutoTokenizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from dataset import *
from model import *
from trainer import Trainer

import torch
torch.manual_seed(333)

In [ ]:
#  PATH = "../"
MAX_LEN = 256
BATCH_SIZE = 128

# Loading data

In [6]:
train_data = pd.read_csv(os.path.join(path_gv, "train.csv"))
test_data = pd.read_csv(os.path.join(path_gv, "test.csv"))

train_data.head()

   rate                                               text
0     4  Очень понравилось. Были в начале марта  с соба...
1     5  В целом магазин устраивает.\nАссортимент позво...
2     5  Очень хорошо что открылась 5 ка, теперь не над...
3     3  Пятёрочка громко объявила о том как она заботи...
4     3  Тесно, вечная сутолока, между рядами трудно ра...

# Label encoding

In [7]:
le = LabelEncoder()

train_data.rate = le.fit_transform(train_data.rate)
train_data.head()

   rate                                               text
0     3  Очень понравилось. Были в начале марта  с соба...
1     4  В целом магазин устраивает.\nАссортимент позво...
2     4  Очень хорошо что открылась 5 ка, теперь не над...
3     2  Пятёрочка громко объявила о том как она заботи...
4     2  Тесно, вечная сутолока, между рядами трудно ра...

# Train Test split

In [8]:
train_split, val_split = train_test_split(train_data, test_size=0.85, random_state=333)

# Loading tokenizer from pretrained

In [9]:
tokenizer = AutoTokenizer.from_pretrained(
    "cointegrated/rubert-tiny2", truncation=True, do_lower_case=True)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/693 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/401 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

# Creating datasets and dataloaders

In [10]:
test_data['rate'] = 0

In [11]:
train_dataset = FiveDataset(train_split, tokenizer, MAX_LEN)
val_dataset = FiveDataset(val_split, tokenizer, MAX_LEN)
test_dataset = FiveDataset(test_data, tokenizer, MAX_LEN)

In [12]:
train_params = {"batch_size": BATCH_SIZE,
                "shuffle": True,
                "num_workers": 0
                }

test_params = {"batch_size": BATCH_SIZE,
               "shuffle": False,
               "num_workers": 0
               }

train_dataloader = DataLoader(train_dataset, **train_params)
val_dataloader = DataLoader(val_dataset, **test_params)
test_dataloader = DataLoader(test_dataset, **test_params)

# Loading pretrained model from Huggingface

In [13]:
config = {
    "num_classes": 5,
    "dropout_rate": 0.3
}
model = ModelForClassification(
    "cointegrated/rubert-tiny2",
    config=config
)

model.safetensors:   0%|          | 0.00/118M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/55 [00:00<?, ?it/s]

BertModel LOAD REPORT from: cointegrated/rubert-tiny2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.embeddings.position_ids               | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

# Creating Trainer object and fitting the model

In [14]:
trainer_config = {
    "lr": 2e-5,
    "n_epochs": 10,
    "weight_decay": 1e-6,
    "batch_size": BATCH_SIZE,
    "device": "cuda" if torch.cuda.is_available() else "cpu",
    "seed": 333,
}
t = Trainer(trainer_config)

In [15]:
t.fit(
    model,
    train_dataloader,
    val_dataloader
)

Epoch 1/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.5728859305381775
Epoch 2/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.6309529542922974
Epoch 3/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.6381085515022278
Epoch 4/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.64753657579422
Epoch 5/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.6520813703536987
Epoch 6/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.6532900929450989
Epoch 7/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.6573755741119385
Epoch 8/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.6550548672676086
Epoch 9/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.6555383205413818
Epoch 10/10

  0%|          | 0/115 [00:00<?, ?it/s]

  0%|          | 0/647 [00:00<?, ?it/s]

0.6557559370994568

ModelForClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(83828, 312, padding_idx=0)
      (position_embeddings): Embedding(2048, 312)
      (token_type_embeddings): Embedding(2, 312)
      (LayerNorm): LayerNorm((312,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-2): 3 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=312, out_features=312, bias=True)
              (key): Linear(in_features=312, out_features=312, bias=True)
              (value): Linear(in_features=312, out_features=312, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=312, out_features=312, bias=True)
              (LayerNorm): LayerNorm((312,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=312, out_features=600, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=600, out_features=312, bias=True)
            (LayerNorm): LayerNorm((312,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=312, out_features=312, bias=True)
      (activation): Tanh()
    )
  )
  (pre_classifier): Linear(in_features=312, out_features=768, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (classifier): Linear(in_features=768, out_features=5, bias=True)
)

# Save model

In [16]:
t.save("baseline_model.ckpt")

In [ ]:
# path_full = path_gv + "baseline_model.ckpt"
# t.save(path_full)

# Load pretrained Model

In [18]:
t = Trainer.load("baseline_model.ckpt")

Loading weights:   0%|          | 0/55 [00:00<?, ?it/s]

BertModel LOAD REPORT from: cointegrated/rubert-tiny2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
bert.embeddings.position_ids               | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

# Get testset predictions

In [19]:
predictions = t.predict(test_dataloader)

# Create submission

In [20]:
sample_submission = pd.read_csv(os.path.join(path_gv, "sample_submission.csv"))
sample_submission["rate"] = predictions
sample_submission.rate = le.inverse_transform(sample_submission.rate)
sample_submission.head()

   index  rate
0      0     5
1      1     4
2      2     5
3      3     3
4      4     1

In [21]:
# sample_submission.to_csv(path_gv + "submission.csv", index=False)

In [ ]:
sample_submission.to_csv(path_gv + "submission_006.csv", index=False)